# UFT Digital Lab Configuration
# =============================================================================

[appium]
hub.url = https://na90uftl001-sal.delhaize.com:8443/wd/hub  
platform = Android
automation.name = UiAutomator2
no.reset = true
new.command.timeout = 300

[oauth]
client.id = oauth2-LVCNXZWYQnDZK3wvBwE5@microfocus.com
client.secret = wA1mILifsuTxFNAHrebf
tenant.id = 999999999

[device]
udid = 22325524700299
name = ET40- raj grind log

[app]
package = com.microsoft.emmx
activity = org.chromium.chrome.browser.webapps.SameTaskWebApkActivity

